# Basic dependabot.yml file with
# minimum config for packagemanager

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root`
    directory: "/"
    # Check the npm registry for updates every day(weekdays)
    schedule:
      interval: "daily"
