name: Netlify Scheduled Deployment

on:
  schedule:
    - cron: '0 8 * * 0' # Every Sunday at 8:00 AM UTC
  workflow_dispatch: # Allows manual triggering of the action from GitHub Actions

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Netlify Build with Cache Clearing
        run: |
          # Call the Netlify API to trigger a new build and clear the cache
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.NETLIFY_ACCESS_TOKEN }}" \
          -d '{"clear_cache": true}' \
          https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/builds
