name: Netlify Scheduled Deployment

on:
  schedule:
    - cron: "0 8 * * 0" # Every Sunday at 8:00 AM UTC
  workflow_dispatch: # Allows manual triggering of the action from GitHub Actions

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Fetch data from Notion
        run: npm run fetch-data
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_KEY }}

      - name: Build project
        run: npm run build
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_KEY }}

      - name: Trigger Netlify Build with Cache Clearing
        run: |
          # Call the Netlify API to trigger a new build and clear the cache
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.NETLIFY_ACCESS_TOKEN }}" \
          -d '{"clear_cache": true}' \
          https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/builds
